### PR TITLE
cookie delete bug

### PR DESCRIPTION
**Pull request by Gtskk**
It should be "delete" instead of "remove" on line 266.

### CODE REVIEW

**Comment by websanova** [comment]
Nope, it should be `remove`, it's been updated. Did you grab the latest?

**Comment by Gtskk** [comment]
Yes, I have grabbed the latest. But I get the following error:

> Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
    at Auth._logoutProcess (eval at <anonymous> (app.js:278), <anonymous>:266:24)
    at Auth._invalidToken (eval at <anonymous> (app.js:266), <anonymous>:37:34)
    at Auth._responseIntercept (eval at <anonymous> (app.js:278), <anonymous>:133:45)
    at eval (eval at <anonymous> (app.js:266), <anonymous>:27:15)
    at <anonymous>

The error is on line 266 of auth.js.

**Comment by websanova** [comment]
doh, try `v2.16.1-beta`. sry about that.

**Comment by Gtskk** [comment]
😆

**Pull request closed without merging**
