### PR TITLE
add config options to set individual rememberme cookie name and cookie expire offset

### PR DESCRIPTION
**Pull request by lexusburn**
I need to set an individual cookie expire offset, instead the default 14 days. Therefore i've added the option to setup it. 

And because it's possible to set token name, i had added the possibility to set an individual name for rememberme cookie too.

### CODE REVIEW

**Comment by heartbeatLV** [comment]
i have the same problem with cookie expire offset

**Comment by websanova** [comment]
@heartbeatLV @lexusburn I have done some updates with cookies to make it a lot more flexible (this is with updates on version 3 btw, so please update).

Notes on new cookie setup here: https://websanova.com/docs/vue-auth/guides/cookies

**Comment by heartbeatLV** [comment]
@websanova I have updated the library from version 3.0.9-beta to 3.1.2-beta. Previously cookies were saved now no longer. Ideas?

**Comment by heartbeatLV** [comment]
> 
> 
> @websanova I have updated the library from version 3.0.9-beta to 3.1.2-beta. Previously cookies were saved now no longer. Ideas?

I understand what the problem is:
The default configuration of cookies sets `Secure;` therefore, on an unsecured connection, cookies are not saved

**Pull request closed without merging**
