### PR TITLE
add sessionstorage support

### PR DESCRIPTION
**Pull request by mannes**
adds support for session storage.
Using session storage you can tie the token to your browser session and you will be 'logged out' after closing the window/tab

### CODE REVIEW

**Comment by potatoru** [comment]
Right in time! Thank you.

**Comment by mannes** [comment]
> Right in time! Thank you.

Grab the first commit, i was testing some other things in the same branch also....

Anyway, this repo seem pretty deserted. Not sure anyone will ever look at this/merge it

**Comment by mannes** [comment]
i restored the branch so it can be merged to add this funcitonality @websanova

**Comment by pdroge84** [comment]
Really needing this functionality. @websanova  Could this please be merged?

**Comment by websanova** [comment]
@pdroge84 alright this is in `v2.22.0-beta`

thx, :-)

**Pull request merged**
