### PR TITLE
added axios http driver

### PR DESCRIPTION
**Pull request by LowM4N**

### CODE REVIEW

**Comment by LowM4N** [comment]
If you use Axios like this:

```
import axios from 'axios'

axios.post(...).then(res => {
  console.log('RES', res)
})
```

then it will use the default global instance from Axios and it will works.

But if you create your own instance of Axios like this:

```
import axios from 'axios'

let myInstance = axios.create({
  baseURL: 'https://some-domain.com/api/',
  timeout: 1000,
  headers: {'X-Custom-Header': 'foobar'}
})

myInstance.post(...).then(res => {
  console.log('RES', res)
})
```

then the interceptors aren't appended to this instance and the authorization header will be missing on it. For this case, you must pass the custom instance to the driver.

A solution for that, is creating a factory function that accept some options or a other way to set the custom instance for the driver. In my case I don't needed that because I use the global instance, but I can implement a solution for that.

**Comment by LowM4N** [comment]
Now it is possible to pass the custom instance to the driver with:

```
import axios from 'axios'
import VueAuth from '@websanova/vue-auth'
import { AuthBearer } from './auth'

let myInstance = axios.create({
  baseURL: 'https://some-domain.com/api/',
  timeout: 1000,
  headers: {'X-Custom-Header': 'foobar'}
})

Vue.use(VueAuth, {
  auth: AuthBearer,
  http: require('@LowM4N/vue-auth/drivers/http/axios.js')(myInstance),  // if you call the function without params, then it will use the global axios instance
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js')
  ...
})

myInstance.post(...).then(res => {
  console.log('RES', res)
})
```

**Comment by guilhermewaess** [comment]
@LowM4N Nice!!

There is a prevision to know when this pr will be reviwed?

**Comment by websanova** [comment]
I still need to test it a bit. I'm worried about inconsistency with the
other drivers. Where router has a requirement like Vue.router and this one
is passed in. Not sure which way would be better. I think it might be
better to just have like a Vue.http = new Axios instance. Also I'm always
weary of seeing a require in an if/else statement. Just want to make sure
this is not increasing the file size when webpack does it's thing.

Haven't had time at the moment to play with it. You're free to just
copy/paste it into your projects for now.

**Comment by websanova** [comment]
After thinking about it now, this most definitely will end up including the
axios code twice in the project. Right now vue-auth is coming from the the
src folder, so webpack would probably be smart enough to pick up the
require('axios') and only include it once.

However this is only because I have had issues with the build. Ideally it
should be coming from the dist directory already built and minified. In
that case the app would most likely end up including the axios file again
and potentially even a different version.

I guess the build can be set to skip require statements. But not sure what
is best practice here at the moment.

**Comment by LowM4N** [comment]
@websanova The driver now use the [vue-axios](https://github.com/imcvampire/vue-axios) plugin, to get the instance. I think this is the best solution for now.

```
import Vue from 'vue'
import axios from 'axios'
import VueAxios from 'vue-axios'
import VueAuth from '@websanova/vue-auth'

Vue.use(VueAxios, axios)
Vue.use(VueAuth, {
  auth: AuthBearer,
  http: require('@websanova/vue-auth/drivers/http/axios.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js')
  ...
})

// access axios with Vue or use the 'this' reference in components
Vue.axios.post(...).then(res => {
  console.log('RES', res)
})
```

**Comment by jgerbes** [comment]
Is this branch going to be merged into the master?

**Comment by websanova** [comment]
Yes, likely, I just haven't had a chance to take a look yet.

**Comment by jgerbes** [comment]
Thanks for confirming. Do you have any idea when you may be able to review it?

**Comment by websanova** [comment]
Next week I think, I'm just swamped with 3 client projects a the moment.
Need to get a couple of my plate first. Thx for the patience so far.

**Comment by websanova** [comment]
Hey, I need to update the example for usage, but I can't get the baseURL to work.

~~~
Vue.axios({
     baseURL: 'https://api-demo.websanova.com/api/v1'
 });

Vue.axios.baseURL = 'https://api-demo.websanova.com/api/v1';
~~~

How is this done with axios?

**Comment by gongzza** [comment]
you can set the baseUrl like this
```
Vue.axios.defaults.baseURL = 'https://api-demo.websanova.com/api/v1'
```

but I got error
```
{
    "status": "error",
    "error": "invalid.credentials",
    "msg": "Invalid Credentials."
}
[Error] Failed to load resource: the server responded with a status of 400 (HTTP/2.0 400) (login, line 0)
```

**Comment by gongzza** [comment]
and I guess you need to update your axios example like this
```
Vue.use(VueAuth, {
    auth: AuthBearer,
-   http: require('@websanova/vue-auth/drivers/http/axios.js'),
+   http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
    router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js')
    ...
});
```

**Comment by jkirkby91-2** [comment]
@gongzza when i try this i get 

Error (@websanova/vue-auth): axios.js : Vue.axios must be set.
Auth @ auth.js?9c12:460
install @ index.js?7b69:7
Vue.use @ vue.esm.js?65d7:3759
(anonymous) @ index.js?3672:31
(anonymous) @ index.js?3672:30
(anonymous) @ app.js:1015
__webpack_require__ @ app.js:660
fn @ app.js:84
(anonymous) @ main.js?1c90:6
(anonymous) @ app.js:827
__webpack_require__ @ app.js:660
fn @ app.js:84
(anonymous) @ app.js:1261
__webpack_require__ @ app.js:660
(anonymous) @ app.js:709
(anonymous) @ app.js:712

**Comment by websanova** [comment]
Ya, so it means you didn't set Vue.axios, you can set it directly or use
vue-axios

**Pull request merged**
